language: php

php:
  - 7.1

before_script:
  - cp .env.travis .env
  - touch database/database.sqlite
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - php artisan key:generate
  - php artisan migrate

script:
  - phpunit

services:
  - sqlite

notifications:
  email: false
